DROP TABLE IF EXISTS Film_Likes, GENRE, RATING, USERS, Film, Friendship, Friendship_status, Films_Genres;

CREATE TABLE IF NOT EXISTS Film_Likes
(
    Film_id INT,
    User_id INT
);

CREATE TABLE IF NOT EXISTS Genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(40)
    );

CREATE TABLE IF NOT EXISTS Films_Genres
(
    Film_id INTEGER,
    Genre_id INTEGER
);
CREATE TABLE IF NOT EXISTS Rating
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(40)
    );
CREATE TABLE IF NOT EXISTS Friendship_status
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name varchar(40)
    );
CREATE TABLE IF NOT EXISTS Friendship
(
    User_id   INTEGER,
    Friend_id INTEGER,
    Status_id INTEGER REFERENCES Friendship_status
);

CREATE TABLE IF NOT EXISTS Film
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name         varchar(200),
    Description  varchar(200),
    Release_Date DATE,
    Duration     INT,
    MPA int
    );

CREATE TABLE IF NOT EXISTS Users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Email    varchar(100),
    Login    varchar(40),
    Name     varchar(200),
    Birthday DATE
    );



